[package]
name = "cachesim"
version = "0.1.0"
edition = "2021"

[dependencies]
cachelib = { path = "../cachelib" }
clap = { version = "4.1.4", features = ["derive"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
memmap2 = "0.5.8"